Variables-2 update
VeritasX/teaching-web-dev pull request #2
Opened 2017-08-28 20:22 UTC by Cr1msonFir3

fixed a hyperlink in both variable-2 files and added solutions to the variable-2 solutions.

2017-08-28 20:40 UTC, aaronendsley requested changes
Try changing  the variable names of your numbers in your multiplication and division to match the naming convention of your numbers in your add and subtract variables

2017-09-03 04:20 UTC, Cr1msonFir3 commented
it fixed now

2017-09-03 04:22 UTC, Cr1msonFir3 commented
now it's fixed

2017-09-03 04:24 UTC, aaronendsley approved these changes

2017-09-03 04:24 UTC, merged